## 2.2.1 创建NDArray

In [1]:
from mxnet import nd

In [2]:
x = nd.arange(12)  # 创建行向量
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [3]:
x.shape  # 形状

(12,)

In [4]:
x.size  # 元素总数

12

In [5]:
X = x.reshape((3, 4))  # 重排为3行4列的矩阵
# X = x.reshape((-1, 4))
# X = x.reshape((3, -1))
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [6]:
nd.zeros((2, 3, 4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [7]:
nd.ones((3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [8]:
Y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])  # 指定每个元素值
Y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [9]:
nd.random.normal(0, 1, shape=(3, 4))  # 一个形状为(3, 4)服从0均值 1方差的正态分布的NDArray


[[ 1.1630787   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.5580711  -0.5459446  -2.3556297 ]
 [ 0.5414402   2.6785066   1.2546344  -0.54877394]]
<NDArray 3x4 @cpu(0)>

## 2.2.2 运算

In [10]:
X + Y  # 加法


[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [11]:
X * Y  # 乘法


[[ 0.  1.  8.  9.]
 [ 4. 10. 18. 28.]
 [32. 27. 20. 11.]]
<NDArray 3x4 @cpu(0)>

In [12]:
X / Y  # 除法


[[ 0.    1.    0.5   1.  ]
 [ 4.    2.5   2.    1.75]
 [ 2.    3.    5.   11.  ]]
<NDArray 3x4 @cpu(0)>

In [13]:
Y.exp()  # 指数运算


[[ 7.389056   2.7182817 54.59815   20.085537 ]
 [ 2.7182817  7.389056  20.085537  54.59815  ]
 [54.59815   20.085537   7.389056   2.7182817]]
<NDArray 3x4 @cpu(0)>

In [14]:
nd.dot(X, Y.T)  # X与Y的转制矩阵乘法


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [15]:
# 连结
print(nd.concat(X, Y, dim=0))  # 维度0 - 行
print(nd.concat(X, Y, dim=1))  # 维度1 - 列


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]]
<NDArray 6x4 @cpu(0)>

[[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]
<NDArray 3x8 @cpu(0)>


In [16]:
X == Y  # 相同位置值相等为1 否则为0


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [17]:
X.sum()  # 求和


[66.]
<NDArray 1 @cpu(0)>

In [18]:
X.norm().asscalar()

22.494442

## 2.2.3 ⼴播机制

In [19]:
A = nd.arange(3).reshape((3, 1))  # 3行1列
B = nd.arange(2).reshape((1, 2))  # 1行2列
A, B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>,
 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [20]:
A + B  # 广播机制 - 先适当复制元素时NDArray形状相同再按位运算


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

## 2.2.4 索引

In [21]:
X[1:3]  # ⾏索引


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [22]:
X[1, 2] = 9
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  9.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [23]:
X[1:2, :] = 12  # 行索引为1的每一列重新赋值
X


[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

## 2.2.5 运算的内存开销

In [24]:
# 每一个操作都需重新开辟内存
before = id(Y)
Y = Y + X
id(Y) == before

False

In [29]:
# 指定结果到特定内存
Z = Y.zeros_like()  # 全0的NDArray
before = id(Z)
Z[:] = X + Y  # 相当于浅拷贝 - 为X+Y开辟临时内存再拷贝到Z对应的内存
id(Z) == before

True

In [30]:
nd.elemwise_add(X, Y, out=Z)  # 避免临时内存
id(Z) == before

True

In [33]:
before = id(X)
X += Y
id(X) == before

True

## 2.2.6 NDArray和NumPy相互变换

In [36]:
import numpy as np
P = np.ones((2, 3))
D = nd.array(P)  # 使用array类型转换
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [38]:
D.asnumpy()  # NDArray转numpy

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)